# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TheGoodFridge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheGoodFridge
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Alamofire','~> 5.1'
end
